[project]
name = "benbot"
version = "0.1.0"
description = "BenBot is a simple LLM + RAG library with persistence."

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]